services:
  - type: web
    name: golfight
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.app:app --host 0.0.0.0 --port $PORT
